### ISSUE TITLE
部署后创建admin用户，然后创建报警组报错

### ISSUE THREAD

**Issue by sjkcdpc** [URLooker/wiki#7]
![image](https://user-images.githubusercontent.com/12950929/55150883-0acb2b80-5188-11e9-8b87-de15e890f331.png)

**Comment by liziker** [comment]
问题解决了吗兄弟，我也遇到这个问题

**Comment by sjkcdpc** [comment]
没解决 个人判断和代码逻辑有关系 因为不着急用就忽略了

**Comment by 710leo** [comment]
@mds1455975151 @liziker 我本地测试没有问题，其他用户也有反馈，发现是前端浏览器不兼容导致的，换个浏览器试试就可以了
